name: Pack Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install ZIP
        uses: montudor/action-zip@v1
        
      - name: Setup NPM packages
        run: npm install
        
      - name: Pack extension
        run: npm run build-action

      - name: Unzip extension
        run: unzip -qq ./build/OldTwitterChrome.zip -d ./build/OldTwitterChrome; unzip -qq ./build/OldTwitterFirefox.zip -d ./build/OldTwitterFirefox
        working-directory: ${{ github.workspace }}
        
      - name: Upload for Firefox
        uses: actions/upload-artifact@v4
        with:
          name: OldTwitterFirefox
          path: ${{ github.workspace }}/build/OldTwitterFirefox
      - name: Upload for Chromium
        uses: actions/upload-artifact@v4
        with:
          name: OldTwitterChrome
          path: ${{ github.workspace }}/build/OldTwitterChrome
